- name: Check satellite registration
  command: "linstor --machine --output-version v1 node list --nodes {{ inventory_hostname }}"
  register: node_list_output
  changed_when: no

- name: Register satellite
  command: "linstor node create {{ inventory_hostname }}"
  when: 'not (node_list_output.stdout | from_json)[0]'
