test_suite_file = "run.toml"

[tests]
[tests.iscsi-create]
vms = [3]

[tests.iscsi-dirty-delete]
vms = [3]

[tests.nfs-create]
vms = [3]

[tests.nvme-create]
vms = [3]

[tests.healthcheck]
vms = [1]

[tests.create-same-name]
vms = [3]

[tests.create-same-ip]
vms = [3]
